### ISSUE TITLE
Clarification on how to load products with multiple variants. 

### ISSUE THREAD

**Issue by ehutzle** [grll/saleor-gql-loader#5]
Looking at the create_product_variant function, I only see specification for one variant-attribute.

```
variant_id = etl_data_loader.create_product_variant(
                                                  product_id,
                                                  sku=product["sku"].replace("-00","-1{}".format(i + 1)),
                                                  attributes=[
                                                  {"id": qty_attribute_id, "values": [qty]}],
                                                  costPrice=product["price"],
                                                  weight=0.75,
                                                  stocks=[{"warehouse": warehouse_id, "quantity": 15}])
```

Is there a way to pass a list of attribute ids in a dictionary to the function, I took a look at the code but wasn't able to find out by myself.

**Comment by ehutzle** [comment]
Here's what I wrote to handle this.

    def create_product_variant(self, product_id, sku, attribs, price):

        input = {
            "sku": sku,
            "attributes": attribs,
            "priceOverride": price
        }

        variables = {
            "input": input,
            "product": product_id
        }
        variables = MyDict(variables)
        query = """
            mutation createProductVariant($input: ProductVariantBulkCreateInput!, $product: ID!) {
                productVariantBulkCreate(variants: [$input], product: $product) {
                    productVariants {
                        id
                    }
                    bulkProductErrors {
                        field
                        message
                        code
                    }
                    count 
                }
            }
        """

        response = graphql_request(
            query, variables, self.headers, self.endpoint_url)
        id = response["data"]["productVariantBulkCreate"]["productVariants"]
        for x in id:
            id_val = x['id']

        errors = response["data"]["productVariantBulkCreate"]["bulkProductErrors"]
        handle_errors(errors)

        return id_val

**Comment by grll** [comment]
the way I was doing it was creating product variants in a for loop, if I find the time I will add the bulk version you posted here to the code ! Thanks
