### ISSUE TITLE
Create Image Issue 2.10

### ISSUE THREAD

**Issue by allidoisace** [grll/saleor-gql-loader#8]
Using the built in `create_product_image` there seems to be an issue running this method since it results in the exception below. I also printed out the body information. It is not immediately clear to me of why the query is not valid.

```
<MultipartEncoder: {'operations': '{"query": "\\n        mutation ProductImageCreate($product: ID!, $image: Upload!, $alt: String) {\\n            productImageCreate(input: {alt: $alt, image: $image, product: $product}) {\\n                image{\\n                    id\\n                }\\n                productErrors {\\n                    field\\n                    message\\n                }\\n            }\\n        }\\n    ", "variables": {"product": "UHJvZHVjdDo3Mg==", "image": "0", "alt": ""}}', 'map': '{"0": ["variables.image"]}', '0': ('test.png', <_io.BufferedReader name='test.png'>, 'image/png')}>
```
```
Exception: Must provide a query string.
 extensions: {'exception': {'code': 'ValueError', 'stacktrace': ['ValueError: Must provide a query string.']}}
```

**Comment by ehutzle** [comment]
I've dealt with this too. 

My fix was to use https://github.com/DoctorJohn/aiogqlc for any multi-part requests.

**Comment by bruw** [comment]
Fix: 
in `graphql_multipart_request `when calling request.post you should pass in `headers=base_headers`:
`    response = requests.post(
        endpoint, data=bodyEncoder, headers=base_headers, timeout=90
    )
`
That is because the override dict does the override on the first object, not the last. So the "headers" are missing the "multipart" header.

**Comment by fkhadra** [comment]
Hey @artdiev, just to let you know that the latest version with this fix is not published to pip. I had to clone the repo and install it manually. 

Cheers

**Comment by grll** [comment]
> Hey @artdiev, just to let you know that the latest version with this fix is not published to pip. I had to clone the repo and install it manually.
> 
> Cheers

Hi @fkhadra thanks for the reminder, indeed I just quickly merged the PR. I will make a new release soon with updated pip package

**Comment by KavinJey** [comment]
Not sure if this has been fixed...had to add what  @artdiev did to source to get it to work. 

Should picture type also be passed as an arg as assuming the image is a png reduces versatility (had to change this to jpg for myself)?

**Comment by grll** [comment]
Hey, I just pushed the new releases with the fixes mentioned on pypi. Sorry for the delay.
